### ISSUE TITLE
Waveshare 6" e-Paper

### ISSUE THREAD

**Issue by grkngls** [robweber/omni-epd#51]
Will be there a driver for the Waveshare 6inch (1448×1072) e-Paper (https://www.waveshare.com/6inch-HD-e-Paper-HAT.htm)?

So it could be used with the [SlowMovie Player](https://github.com/TomWhitwell/SlowMovie).

**Comment by robweber** [comment]
There have been a few requests for this. The biggest hurdle currently is the lack of an official Python driver for that device, since that is what this project and most supplementary projects (like SlowMovie) use to interface with the EPD device. 

In #48 I did reference a third-party library that attempts to make a Python lib for communicating with IT8951 devices. On paper at least, integrating this with `omni-epd` should be possible. The main issue comes down to testing. I don't have access to one of these devices which makes adding it difficult. I did flag that issue as __help wanted__ should anyone want to tackle it.

**Comment by micheledicosmo** [comment]
I tried to make https://github.com/GregDMeyer/IT8951 work with my 7.8'' Waveshare device, but with no luck. I'll keep trying but I fear I might need to adapt the original WaveShare C example code, or at least get a good understanding of how it works to make it work.

At the moment I am getting a generic "connection failed" error right at the beginning of the library code, when it queries the display information, and a no-response/all-zeroes response is received.

**Comment by micheledicosmo** [comment]
Nevermind, I managed to connect, will keep working on making the library behave OK and get back to you. Ta!

**Comment by micheledicosmo** [comment]
Ok I managed to make it work. I would be very happy if you created a stub in a branch for me. Thanks!

**Comment by robweber** [comment]
I'll definitely do that - I'll post back here. Thanks for working on this.

**Comment by robweber** [comment]
I added a new branch here: https://github.com/robweber/omni-epd/tree/it8951. If you want to clone that and submit any changes as  PR that would be great. 

The main file you'll want to work on is the [IT8951Display](https://github.com/robweber/omni-epd/blob/it8951/src/omni_epd/displays/it8951_display.py) class file. This is really just a copy of the Mock class file. For the device name I used _waveshare_epd.it8951_. Go ahead and change that if it makes sense to do so. You can run omni-epd-test with that device name so at least the hooks are in place to load the device by name. 

Hopefully by looking at some of the other implemented classes this will be enough to get the device working in this framework. Let me know if you need me to do anything.

**Comment by robweber** [comment]
I've attempted a start at doing this but need testers as I currently do not have a device. My implementation is based of examples in the repo. Those interested please see #57.
